Repository jenkins-x/jenkins-x-serverless, pull requests merged in 2018-10, with the labels that each got.

#8 chore: updated jx to 1.3.371
  Dockerfile-base
  Dockerfile-go
  Dockerfile-jenkins
  Makefile
  jx-docker-build.sh
Labels: size/M

#10 fix: renamed dockerfiles to work with updatebot
  Dockerfile.base
  Dockerfile.csharp
  Dockerfile.cwp
  Dockerfile.filerunner
  Dockerfile.go
  Dockerfile.gradle
  Dockerfile.javascript
  Dockerfile.jenkins
  Dockerfile.maven
  Dockerfile.python
  Dockerfile.rust
  Dockerfile.scala
  jx-docker-build.sh
Labels: size/M

#11 Added dummy dockerfile
  Dockerfile
Labels: size/XS

#12 update JX_VERSION to 1.3.394
  Dockerfile.base
Labels: size/XS, updatebot

#15 fix: installing hugo as prebuilt binary
  Dockerfile.go
Labels: size/S

#14 Do not include workflow-aggregator
  packager-config.yml
Labels: size/XS

#17 fix: added xvfb to javascript image
  Dockerfile.javascript
Labels: size/XS

#18 feat: pushing jenkins-base image
  jx-docker-build.sh
Labels: size/S

#21 feat: added downstream update of knative chart
  .updatebot.yml
  jx-docker-build.sh
Labels: size/XS

#25 fix: attempting to fix PR creation
  jx-docker-build.sh
Labels: approved, size/XS

#36 fix: reorder script to get around 'docker system prune' issues
  jx-docker-build.sh
Labels: approved, size/S

#54 feat: upgrade gcloud to 222.0.0
  Dockerfile.base
Labels: approved, size/XS
