Repository jenkins-x/jenkins-x-serverless, pull requests merged in 2018-11, with the labels that each got.

#59 Release Build flow - make is now a part of jx-docker-build.sh
  Jenkinsfile
Labels: size/XS

#60 upgrade helm
  Dockerfile.base
Labels: approved, size/XS

#64 Revert1
  .gitignore
  Dockerfile.cwp
  Dockerfile.filerunner
  Jenkinsfile
  Makefile
  jx-docker-build.sh
  packager-config.yml
  test/Jenkinsfile-helloworld
Labels: approved, size/M

#56 Apply core & a few plugin updates
  Dockerfile.filerunner
  Makefile
  packager-config.yml
Labels: approved, size/S

#82 Update to jenkinsci/jenkinsfile-runner
  packager-config.yml
Labels: approved, size/XS

#113 fix: always push docker images, even during PR build
  jx-docker-build.sh
Labels: approved, size/S

#123 feat: add goreleaser
  Dockerfile.base
Labels: approved, size/S
