Repository jenkins-x/jenkins-x-serverless, pull requests merged in 2018-12, with the labels that each got.

#128 feat: initial commit of helm chart for test phase
  Jenkinsfile
  jenkins-x-serverless/Chart.yaml
  jenkins-x-serverless/Makefile
  jenkins-x-serverless/README.md
  jenkins-x-serverless/templates/NOTES.txt
  jenkins-x-serverless/templates/_helpers.tpl
  jenkins-x-serverless/templates/serverless-clusterrole.yaml
  jenkins-x-serverless/templates/serverless-clusterrolebinding.yaml
  jenkins-x-serverless/templates/serverless-configmap.yaml
  jenkins-x-serverless/templates/serverless-job.yaml
  jenkins-x-serverless/templates/serverless-role.yaml
  jenkins-x-serverless/templates/serverless-rolebinding.yaml
  jenkins-x-serverless/templates/serverless-sa.yaml
  jenkins-x-serverless/values.yaml
  jx-docker-build.sh
  jx/scripts/test.sh
Labels: approved, size/L

#143 chore: upgrade images to 2.138.4 LTS
  Dockerfile.filerunner
  packager-config.yml
Labels: approved, size/XS

#144 chore: removed unused test file
  Jenkinsfile-test
Labels: approved, size/S

#155 feat: updating jenkins to latest lts - 2.150.1
  Dockerfile.filerunner
  packager-config.yml
  update-plugins.groovy
Labels: approved, size/XS

#161 update jx-resources plugin
  packager-config.yml
Labels: approved, size/XS

#158 chore: updated to skaffold 0.19.0
  Dockerfile.base
Labels: approved, size/XS

#175 feat: upgrade jx-resources plugin to add ProwEnvironmentContributor
  packager-config.yml
Labels: approved, size/XS

#178 fix: updated jx-resources to 1.0.26 to fix pipeline activities
  packager-config.yml
Labels: approved, size/XS

#190 upgrade helm
  Dockerfile.base
Labels: approved, size/XS

#147 fix: upgrade CasC plugin to 1.3
  .gitignore
  Dockerfile.base
  Dockerfile.cwp
  Dockerfile.filerunner
  Makefile
  casc.yml
  jenkins-x-serverless/templates/serverless-configmap.yaml
  jenkins-x-serverless/templates/serverless-job.yaml
  jx-docker-build.sh
  packager-config.yml
Labels: approved, size/M

#197 fix: using correct version when tagging images
  Dockerfile.filerunner
  Makefile
Labels: approved, size/XS

#202 chore: upgrade skaffold to 0.20.0
  Dockerfile.base
Labels: approved, size/XS
