Repository jenkins-x/jenkins-x-serverless, pull requests merged in 2019-01, with the labels that each got.

#207 Upgrade to Helm 2.12.1
  Dockerfile.base
Labels: approved, ok-to-test, size/XS

#215 Add elixir builder image
  Dockerfile.elixir
  jx-docker-build.sh
Labels: approved, lgtm, ok-to-test, size/S

#226 chore: dependency updates for SECURITY-1266
  pom.xml
Labels: approved, size/S

#240 Add postgresql client utilities
  Dockerfile.base
Labels: approved, lifecycle/active, ok-to-test, size/XS

#253 upgrade helm
  Dockerfile.base
Labels: approved, size/XS

#260 [JENKINS-55239] Update jenkinsfile-runner
  packager-config.yml
Labels: approved, size/XS

#263 added java11 maven builder
  Dockerfile.maven-java11
  jx-docker-build.sh
Labels: approved, ok-to-test, size/S

#264 chore: updated to LTS 2.150.2
  Dockerfile.filerunner
  packager-config.yml
  pom.xml
  update-plugins.groovy
Labels: approved, size/S

#269 Remove some unused plugins
  pom.xml
Labels: approved

#274 chore: remove intermediate image to simpify build
  Dockerfile.base
  Dockerfile.filerunner
  jx-docker-build.sh
Labels: approved, size/M

#289 Updating skaffold to v0.21.1
  Dockerfile.base
Labels: approved, size/XS

#291 fix: update Go version to 1.11.5
  Dockerfile.go
Labels: approved, size/XS

#292 fix: remove chrome browser from base image
  Dockerfile.base
Labels: approved, size/XS

#299 feat: changed base image to reduce build time
  Dockerfile.base
  Jenkinsfile
  Makefile
  casc.yml
  packager-config.yml
  pom.xml
Labels: size/L

#272 feat: using skaffold for serverless builds
  .dockerignore
  Dockerfile.base
  Dockerfile.csharp
  Dockerfile.cwp
  Dockerfile.go
  Dockerfile.javascript
  Dockerfile.jenkins
  Dockerfile.maven
  Dockerfile.rust
  jx-docker-build.sh
  skaffold.base.yaml
  skaffold.csharp.yaml
  skaffold.cwp.yaml
  skaffold.elixir.yaml
  skaffold.go.yaml
  skaffold.gradle.yaml
  skaffold.javascript.yaml
  skaffold.jenkins.yaml
  skaffold.maven-java11.yaml
  skaffold.maven.yaml
  skaffold.python.yaml
  skaffold.rust.yaml
  skaffold.scala.yaml
Labels: approved, size/L

#303 fix: use secret in cluster rather than generating one
  skaffold.base.yaml
  skaffold.csharp.yaml
  skaffold.cwp.yaml
  skaffold.elixir.yaml
  skaffold.go.yaml
  skaffold.gradle.yaml
  skaffold.javascript.yaml
  skaffold.jenkins.yaml
  skaffold.maven-java11.yaml
  skaffold.maven.yaml
  skaffold.python.yaml
  skaffold.rust.yaml
  skaffold.scala.yaml
Labels: approved, size/S

#297 feat: Dockerfile.ruby
  Dockerfile.ruby
  jx-docker-build.sh
  skaffold.ruby.yaml
Labels: approved, ok-to-test, size/M
