Repository jenkins-x/jenkins-x-serverless, pull requests merged in 2019-03, with the labels that each got.

#357 Next gen pipeline
  jenkins-x.yml
  replace-versions.sh
Labels: approved, lgtm, size/L

#361 Turn off parallel builds
  jenkins-x.yml
Labels: approved, lgtm, size/XL

#360 feat: upgrading to skaffold 0.24.0
  Dockerfile.base
Labels: approved, size/XS

#359 Add Update bot
  Dockerfile.base
  Dockerfile.csharp
  Dockerfile.cwp
  Dockerfile.elixir
  Dockerfile.go
  Dockerfile.gradle
  Dockerfile.javascript
  Dockerfile.jenkins
  Dockerfile.maven
  Dockerfile.maven-java11
  Dockerfile.python
  Dockerfile.ruby
  Dockerfile.rust
  Dockerfile.scala
  Jenkinsfile
  jenkins-x.yml
  jx/scripts/test.sh
  replace-versions.sh
Labels: approved, size/XL

#364 switch to latest base buidler with updatebot fixes for running with tekton steps
  jenkins-x.yml
Labels: approved, size/S

#368 switch to GCR for layer caching and released images
  jenkins-x-serverless/values.yaml
  jenkins-x.yml
  jx-docker-build.sh
  skaffold.base.yaml
  skaffold.csharp.yaml
  skaffold.cwp.yaml
  skaffold.elixir.yaml
  skaffold.go.yaml
  skaffold.gradle.yaml
  skaffold.javascript.yaml
  skaffold.jenkins.yaml
  skaffold.maven-java11.yaml
  skaffold.maven.yaml
  skaffold.python.yaml
  skaffold.ruby.yaml
  skaffold.rust.yaml
  skaffold.scala.yaml
Labels: approved, size/L

#382 Update updatebot to 1.1.38
  Dockerfile.base
Labels: approved, size/XS

#379 chore: remove jq as its now in the parent image
  Dockerfile.go
  Dockerfile.jenkins
Labels: approved, size/XS

#396 The entrypoint is the JFR, so it's not expecting this CMD
  Dockerfile.gradle
  Dockerfile.python
Labels: approved, size/XS
