Repository jenkins-x/jenkins-x-serverless, pull requests merged in 2019-07, with the labels that each got.

#608 chore: add changelog.sh
  jenkins-x.yml
  jx/scripts/changelog.sh
Labels: approved, size/XS

#609 chore: switch to the new updatebot
  .updatebot.yml
  jx/scripts/updatebot.sh
Labels: approved, size/XS

#610 fix: correcting changelog script
  jx/scripts/changelog.sh
Labels: approved, size/XS

#615 chore: make changelog.sh executable
  jx/scripts/changelog.sh
Labels: approved, size/XS

#621 chore: bump builder to avoid double tagging
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#632 chore: Add memory requests/limits to pipeline
  jenkins-x.yml
Labels: approved, lgtm, size/S

#644 chore: added precommit configuration
  .pre-commit-config.yaml
  .secrets.baseline
Labels: approved, size/M
